name: ransomware1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.23
  # Remove the problematic build strings (=pypi_0) for Conda to solve these normally
  - anyio=4.10.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=2.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=2.2.1
  - expat=2.7.1
  - gitpython=3.1.45
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - importlib-metadata=8.5.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.5.0
  - ipykernel=6.30.1
  - ipython=8.15.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - json5=0.9.25
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - openssl=3.0.18
  - overrides=7.4.0
  - packaging=25.0
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  
  # Use pip section for packages that originated from PyPI installation
  - pip
  - pip:
    - altair==5.5.0
    - attrs==25.4.0
    - blinker==1.9.0
    - cachetools==6.2.0
    - charset-normalizer==3.4.3
    - click==8.1.8
    - contourpy==1.3.0
    - cycler==0.12.1
    - filelock==3.13.1
    - flask==3.1.2
    - fonttools==4.60.1
    - fsspec==2024.6.1
    - gitdb==4.0.12
    - idna==3.10
    - imageio==2.37.0
    - itsdangerous==2.2.0
    - jinja2==3.1.4
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter==1.1.1
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lime==0.2.0.1
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - mpmath==1.3.0
    - narwhals==2.7.0
    - networkx==3.2.1
    - numpy==1.24.3
    - pandas==2.3.3
    - pefile==2024.8.26
    - pillow==11.0.0
    - pip==25.2
    - protobuf==6.32.1
    - pyarrow==21.0.0
    - pydeck==0.9.1
    - pygments==2.19.1
    - pyparsing==3.2.5
    - pytz==2025.2
    - referencing==0.36.2
